### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sry0** [Cvandia/nonebot_plugin_genshin_cos#16]
**描述bug**
安装后启动报错

**怎么出现的**
安装后启动报错

**异常情况**
安装后启动报错，NameError: name 'get_driver' is not defined

**屏幕截图**
![微信图片_20240722154057](https://github.com/user-attachments/assets/ff83b9e2-89a2-4b41-b61e-17dcfebf8c4e)

**版本情况**
python:3.10.12
nb-cli:1.4.1
pip:24.1.2

**额外的说明**
这里是额外的描述

**Comment by Cvandia** [comment]
我的错，之前更新不小心把`get_driver`删了，马上更新
