### ISSUE TITLE
[BUG]：[Errno 22] Invalid argument: 

### ISSUE THREAD

**Issue by Kiana1314** [Cvandia/nonebot_plugin_genshin_cos#2]
**描述bug**
下载cos中断

**怎么出现的**
发送下载cos指令

**异常情况**
q群报错:
<出错了请查看详细报错:
[Errno 22] Invalid argument: 'data\\genshin_cos\\甘雨cos | 我可以去你的尘歌壶吗？.jpg'>

**屏幕截图**
![IMG_20230331_213431](https://user-images.githubusercontent.com/107671434/229137094-d8a00b0b-7c2c-450d-a9cf-fb114ef3489b.jpg)

**版本情况**
python:3.10.10
nb-cli:1.0.5
pip:23.0.1

**Comment by Cvandia** [comment]
文件路径中包含了一些特殊字符，如`|`和 `？`，这些字符在某些操作系统中可能不被允许用作文件名，后续我尽量把这些特殊字符去除掉
