### ISSUE TITLE
[功能请求]拉黑删除无关图片

### ISSUE THREAD

**Issue by Kiana1314** [Cvandia/nonebot_plugin_genshin_cos#3]
有不是cos的图片，删除后使用下载cos指令还会下载回来，希望可以通过指令拉黑并删除无关或者不喜欢的图片

**Comment by Cvandia** [comment]
可以考虑。获取的图片是实时更新的，短时间重复操作是会下载原图片的，你可以试试过段时间再运行一下指令，或者手动删除不想要的图片

**Comment by Cvandia** [comment]
已解决，尝试更新到最新版本

> 有不是cos的图片，删除后使用下载cos指令还会下载回来，希望可以通过指令拉黑并删除无关或者不喜欢的图片

**Comment by Kiana1314** [comment]
谢谢佬
