### ISSUE TITLE
每天第一次发 原神cos 的时候都会进入10秒cd

### ISSUE THREAD

**Issue by thankU-ubi** [Cvandia/nonebot_plugin_genshin_cos#4]
bot没有报错 
只要第二次发送 原神cos 指令就能正常获取图片并发送

**Comment by Cvandia** [comment]
这个小bug竟然被你发现了！Σ(ﾟдﾟ；)
我之前测试的时候觉得没太大影响，等哪天我再改改

**Comment by Cvandia** [comment]
在[这里](https://github.com/Cvandia/nonebot_plugin_genshin_cos/blob/main/nonebot_plugin_genshin_cos/utils.py#L140-L140)，将后面的timedelta删掉即可

**Comment by Cvandia** [comment]
已更新
