### ISSUE TITLE
[BUG]TypeError: object of type' coroutine' has no len()

### ISSUE THREAD

**Issue by Kiana1314** [Cvandia/nonebot_plugin_genshin_cos#5]
**描述bug**
发送指令不出图

**怎么出现的**
原神cos

**异常情况**
TypeError: object of type' coroutine' has no len()

**屏幕截图**
![-29738e41261c1504](https://user-images.githubusercontent.com/107671434/236633605-ef829893-1792-4c84-b74d-d2c68ce0fa5a.png)
![Screenshot_2023-05-06-23-37-26-281_com tencent mobileqq-edit](https://user-images.githubusercontent.com/107671434/236633685-7461c830-df97-454c-896e-6635924fa87f.jpg)

**版本情况**
python:3.10.10
nb-cli:1.0.5
pip:23.0.1

**Comment by Cvandia** [comment]
我的锅，`get_img_url`函数忘记改成异步 函数了

**Comment by Cvandia** [comment]
> **描述bug** 发送指令不出图
> 
> **怎么出现的** 原神cos
> 
> **异常情况** TypeError: object of type' coroutine' has no len()
> 
> **屏幕截图** ![-29738e41261c1504](https://user-images.githubusercontent.com/107671434/236633605-ef829893-1792-4c84-b74d-d2c68ce0fa5a.png) ![Screenshot_2023-05-06-23-37-26-281_com tencent mobileqq-edit](https://user-images.githubusercontent.com/107671434/236633685-7461c830-df97-454c-896e-6635924fa87f.jpg)
> 
> **版本情况** python:3.10.10 nb-cli:1.0.5 pip:23.0.1

修好了，谢谢纠错(*╹▽╹*)

**Comment by Kiana1314** [comment]
没问题了 谢谢佬
