### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HaHaNiGanMa** [Cvandia/nonebot_plugin_genshin_cos#6]
**描述bug**
输入原神cos不反图

**怎么出现的**
输入原神cos x3

……

**异常情况**
终端报错 KeyError: '_matched_groups'

**屏幕截图**
![@IKXU1225RNNWIJ676X797B](https://github.com/Cvandia/nonebot_plugin_genshin_cos/assets/135359942/549619a8-03ff-46f8-bbe7-5b2fbae29821)

**版本情况**
python:3.10.11
nb-cli:1.1.2
pip:23.1.2
……

**额外的说明**
这里是额外的描述

**Comment by Cvandia** [comment]
可能新版本的nb已经把_matched_groups删了，回头我改一下

**Comment by Cvandia** [comment]
> **描述bug** 输入原神cos不反图
> 
> **怎么出现的** 输入原神cos x3
> 
> ……
> 
> **异常情况** 终端报错 KeyError: '_matched_groups'
> 
> **屏幕截图** ![@IKXU1225RNNWIJ676X797B](https://user-images.githubusercontent.com/135359942/242978740-549619a8-03ff-46f8-bbe7-5b2fbae29821.png)
> 
> **版本情况** python:3.10.11 nb-cli:1.1.2 pip:23.1.2 ……
> 
> **额外的说明** 这里是额外的描述

已更新
