### ISSUE TITLE
下载cos 似乎不会自己创建文件夹

### ISSUE THREAD

**Issue by lancer-wang** [Cvandia/nonebot_plugin_genshin_cos#8]
还是我自己手动创建的
![image](https://github.com/Cvandia/nonebot_plugin_genshin_cos/assets/69783837/51afd878-30ea-4ddc-a40c-5101e90e9e7a)

顺便，能不能配置里面加个选项，选择是否合并转发
合并转发很容易风控的

**Comment by Cvandia** [comment]
好好，收到，等会去改改，感谢！

**Comment by Cvandia** [comment]
> 还是我自己手动创建的 ![image](https://user-images.githubusercontent.com/69783837/249736768-51afd878-30ea-4ddc-a40c-5101e90e9e7a.png)
> 
> 顺便，能不能配置里面加个选项，选择是否合并转发 合并转发很容易风控的

试试更新看看？

**Comment by Cvandia** [comment]
> 还是我自己手动创建的 ![image](https://user-images.githubusercontent.com/69783837/249736768-51afd878-30ea-4ddc-a40c-5101e90e9e7a.png)
> 
> 顺便，能不能配置里面加个选项，选择是否合并转发 合并转发很容易风控的

还有啥需求可以提哦

**Comment by lancer-wang** [comment]
目前应该没有其他啥需求了
