### ISSUE TITLE
[BUG]？

### ISSUE THREAD

**Issue by jx9468** [Cvandia/nonebot_plugin_genshin_cos#9]
**描述bug**
无法正常启用，原先用的版本0.1.6是能正常使用的，现在的0.2.2版本就报错了，是我哪个依赖的版本太低了吗
🤦‍♀️

**怎么出现的**
直接nb run运行

**异常情况**
·

**屏幕截图**
![11a8eee654b4b7e3ebfdd6e9e768348](https://github.com/Cvandia/nonebot_plugin_genshin_cos/assets/78193384/e1f8b8e4-5647-41eb-b556-b16c2398b64a)

**版本情况**
python:3.9.13
nb-cli:1.1.2
pip:23.1.2
nonebot:2.0.0rc4
nonebot-adapter-onebot : 2.2.3

**额外的说明**
这里是额外的描述

**Comment by Cvandia** [comment]
升级nonebot2或者修改删掉type，homepage

**Comment by jx9468** [comment]
> 修改升级nonebot2或者删除类型，主页

好了，原来nonebot2又更新了，感谢😆
